services:
  - type: web
    name: dailypizza-backend
    env: node
    rootDirectory: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 24.14.1
